services:
  - type: web
    name: accident-detection-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_DEBUG
        value: "false"
